[package]
name = "cudart"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cudart-sys = { path = "../cudart-sys" }
bitflags = "*"
paste = "*"

[dev-dependencies]
serial_test = "*"
